# Generated by Django 4.0.2 on 2022-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_elements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elements',
            new_name='Element',
        ),
    ]
