# Generated by Django 4.0.2 on 2022-02-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_rename_elements_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
