# Generated by Django 4.0.3 on 2022-04-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_design'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name_plural': 'Designs'},
        ),
        migrations.RenameField(
            model_name='mockup',
            old_name='base_price',
            new_name='price',
        ),
    ]
