# Generated by Django 4.0.3 on 2022-04-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_alter_design_options_rename_base_price_mockup_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='description',
        ),
        migrations.RemoveField(
            model_name='design',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='design',
            name='price',
        ),
        migrations.RemoveField(
            model_name='design',
            name='stock_code',
        ),
    ]
