# Generated by Django 4.0.2 on 2022-02-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_subcategory_alter_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
